[package]
name = "mark"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
debug = false
opt-level = 3
codegen-units = 1
lto = "fat"

[dependencies]
brotli = "7.0.0"
byteorder = "1.5.0"
lazy_static = "1.5.0"
